# Generated by Django 5.2.1 on 2026-01-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0003_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorreading",
            name="decision",
            field=models.TextField(default="No AI analysis available"),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sensors.device",
            ),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="disease",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="crop_images/"),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="sensor_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="stress_level",
            field=models.CharField(default="Unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="alert",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="humidity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="ph",
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="soil_moisture",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="temperature",
            field=models.FloatField(default=0.0),
        ),
    ]
