# Generated by Django 5.2.1 on 2026-01-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0004_sensorreading_decision_sensorreading_device_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=50)),
                ("disease", models.CharField(max_length=100)),
                ("stress_level", models.CharField(max_length=20)),
                ("condition", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                ("treatment", models.TextField()),
                ("fertilizer", models.TextField()),
                ("spray", models.TextField()),
                ("severity", models.CharField(max_length=20)),
            ],
        ),
    ]
