# Generated by Django 5.2.1 on 2026-01-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0005_croprecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorreading",
            name="crop",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
