# Generated by Django 5.2.1 on 2026-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0006_sensorreading_crop"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorreading",
            name="reading_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
